appKey = ""
appSecret = ""
appSalt = ""

dbConnectionString = "sqlite:///roselia.db"

GITHUB_CLIENT_ID = ''
GITHUB_CLIENT_SECRET = ''

MICROSOFT_CLIENT_ID = ''
MICROSOFT_CLIENT_SECRET = ''

CHEVERETO_API_KEY = ''
CHEVERETO_API_ENDPOINT = ''

SM_MS_API_TOKEN = ''
